### PR TITLE
Don`t assume valid database connection when asking for help

### PR DESCRIPTION
**Pull request by andygrunwald**
See https://github.com/MetricsGrimoire/sortinghat/issues/2

### CODE REVIEW

**Comment by sduenas** [comment]
@andygrunwald Do you mind to update and rebase these changes onto master? There are some conflicts because I merged the bunch of PRs that fixed the code errors.

**Comment by andygrunwald** [comment]
@sduenas I merged master again into this branch. Now we are up to date again.

**Comment by sduenas** [comment]
@andygrunwald Sorry, I completely forgot about this.

I've been trying to merge it but I had problems. There are some conflicts that I can't fix. Do you mind to remove the previous commits and create a new one updated with master?

**Comment by andygrunwald** [comment]
@sduenas Here you find a new updated version with the current master: https://github.com/MetricsGrimoire/sortinghat/pull/64

**Pull request closed without merging**
